// This file is automatically generated. Do not edit it directly.
import { createClient } from "@supabase/supabase-js";
import type { Database } from "./types";

const SUPABASE_URL = "https://unlcrmskawvwsxrinpjv.supabase.co";
const SUPABASE_PUBLISHABLE_KEY =
  "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InVubGNybXNrYXd2d3N4cmlucGp2Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDY0MTg0NDcsImV4cCI6MjA2MTk5NDQ0N30.epXcbs_y5JzcQsO14MbPbGFPRxEAwUww-jfbMkoRUkk";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(
  SUPABASE_URL,
  SUPABASE_PUBLISHABLE_KEY
);
